
INSERT INTO label (label, createdAt, updatedAt)
VALUES
('A', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('B', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('C', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('D', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('E', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('F', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('G', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('H', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);