
INSERT INTO label (id, label, name, createdAt, updatedAt)
VALUES
(1,'A','Cultura', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2,'B','Economía', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3,'C','Educación', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4,'D','Medio Ambiente', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5,'E','Medios de Comunicación', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6,'F','Política', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(7,'G','Sanidad', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(8,'H','Otros temas', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);